language: python

env:
  global:
    secure: "kU2A450zpKsF6lnmZcakvL7k1OWVhJyh9/1aHmIT+Npu7Nt6sdukkw0KCcxYkJbC1Ap0+l1lK7FMGVwgdXauiR5ibxTs0cw1QtU9Sbx1xxHKpNdXFy+LSYbJGppdClEJ7eZh+FUdYbCkRCTLuaCvUoOO/I6AuOq79ewplpGIwqhTUZmVvEBj1Ri8aab99TLk/AnzrJEMG6XKbpneyl1VfmhDu3qImWGRvm66R/2pWVvvVC37GJdeWcx64NZLoRSUzkMahujUnGh/XK7uqJgItP9Juz9lS6fYHX47sk2Y9nOyythpUe+Eyg+7YwQTOPAi3NGNsJ8O3+qfgZCnXB0b0JZXlkjKFX0tgOLHawOFlEI9Ll26IYrIFnx0R1WZftrqHmxIe6oP6eWVlVR0BHGM46GBDLv03gBeWRl6yjBY6qtDKTJNx7dmwvRTLtS6V0bTt53gA9da+jusDwcYFtwMwhYHG/heiQPbiwy4wFRzOU+LJ35YUY8VOePz8i8CRB/vryefVIzntkGKmw1uKkzEwSgSIt5pszh5FmjPV1AuLBVmqgxSulm0ZlMWpVRWEM9YBDmf+T8TD5JkAUhv/vxHmRJrmXj4m1PX13uI93HOLoV2gAi8/OC+FGDcMai8Q6kREKvSHXI6hYXLT+2wfGL5XJ5ng8LCqGV6NCOBmF1oQZU="

python:
  - 3.8
  - 3.7

install:
  - pip install -U tox-travis
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script:
  # lint
  - flake8 centra_py_client
  # test
  - tox
  - pytest -v

before_deploy:
  - bump2version --verbose minor
deploy:
  provider: pypi
  username: "__token__"
  distributions: "sdist bdist_wheel"
  password:
    secure: cU97I0BBcdCRdSJDtRXkhSfoldrgqE5uGL3g7Oiofb7dK5v8K+uLbfYOJ7g/SPwMn8EoKCnuk2jBcDvXRh3J20YuZqFH4/k3LblgyKRt/GuqXRtcBelyvrsDgzdqcx22c2wcQ9Z1dSz+o8Dt03EpiPrXHQMtF8AO+R4jWy33vUcqIqgkoxVakvnDyZsVSFUPkYYgdg0yg14IqH6wd5TxjoVevcpR67wC5SpFeCJarhsNnO+i5zMaub1yJ6xv2BeiycmjHePgGw4avrmdT5RmOhtbIvwFOqMru7a0PYyq64g47Pd6hDW4Iw//LjQwY0OcCZJ7L8vPOWsxvAkN1qVR0PhZi5vlbqlbGEHlrIdVbBtWoUXiHQTi7b3q9oygs6bTtgWbz7LW7G6/teZpZ7KePnU2aXAc8tjA0BdxJIqhZVe2zE5k1B8wkA+mV9L+oRRaNaM6ZjWFeiyUOZPpx7dgNkhrfAnOGC15DOBo8bcjm0QlvCTG0ZCF7Xmy8fjyvIZ+Xhrk+jgFjzBg8xGfIFfjCt4XbF49LOufB5dR06sGehKgp3bkZSSvu8rrb3yPtW8ERknKYfzHsFWK3CwFevJ7VjGm1eDZu3h1Q7JQsRPADjT4AuulDXz40sBfzeSs7Z9pTe9wz3UR3lp63xC7gdzoHEuzQ86SbU5gh+sf2H0P9mI=
  on:
    branch: main
  skip_existing: true
after_deploy:
  - git log -n 4
  - git status
  - git diff HEAD HEAD~1
  - git push origin main
  - git push --tags
